# Update EventLanes diagram images in markdown files on push
name: EventLanes Diagrams (Push)

on:
  push:
    branches: [main]
    paths: ['**/*.md']

permissions:
  contents: write

jobs:
  diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ismasan/eventlanes-gh-action@v1
        with:
          api-token: ${{ secrets.EVENTLANES_API_TOKEN }}
